### ISSUE TITLE
Mixed content when behind ssl-terminating proxy

### ISSUE THREAD

**Issue by dimm0** [perfsonar/maddash#102]
The plots worked fine when ssl-terminating proxy was connecting to https port. When switched to http port, the plots in iframe are not loading anymore, and there's an error in the browser:

Mixed Content: The page at 'https://perfsonar.nrp-nautilus.io/maddash-webui/details.cgi?uri=/maddash/grids/Nautilus+Mesh+-+Latency+eastceph+-+Loss/evldtn.evl.uic.edu_internal/k8s-gen4-01.ampath.net_internal/Packet+Loss' was loaded over HTTPS, but requested an insecure frame 'http://perfsonar.nrp-nautilus.io/perfsonar-graphs/?source=10.244.55.45&dest=10.244.230.216&displaysetdest=&url=https://perfsonar.nrp-nautilus.io/esmond/perfsonar/archive/&reverseurl=https://perfsonar.nrp-nautilus.io/esmond/perfsonar/archive/&displaysetsrc='. This request has been blocked; the content must be served over HTTPS.

**Comment by dimm0** [comment]
@arlake228  ?

**Comment by tonin** [comment]
There is no MaDDash configuration to make this work, from MaDDash perspective, all URLs are considered relative.  Our suggestion is that you keep connecting to the HTTPS port on the whole end-to-end session, both to and from your proxy.
