### ISSUE TITLE
Update log4j to the latest version

### ISSUE THREAD

**Issue by jonstout** [perfsonar/maddash#103]
The current version of log4j used in this project is 1.2.9. The 1.X train of log4j was considered "end of life" in 2015, and numerous security vulnerabilities have been discovered throughout this package's lifetime. As such, use of security scanners like nessus and qualys will flag all systems running Maddash. For environments where regular security audits are performed, this adds additional burden on the operations and security teams.

Please update log4j to the latest version.

**Comment by tmeader** [comment]
@mfeit-internet2 Can this also be closed, in light of the state of MaDDash as noted in #114 ?

**Comment by mfeit-internet2** [comment]
@tmeader All issues and pull requests will be closed and this repository will be archived shortly.
