### ISSUE TITLE
Clarify what the top and bottom of boxes means

### ISSUE THREAD

**Issue by arlake228** [perfsonar/maddash#19]
It's currently confusing what the top and bottom of a box means. Making matters more confusing is the fact that the semantics vary depending on the dashboard. For example, sometimes it's forward and reverse direction other times its the same direction but as reported by different hosts. We need a way to convey what the directions mean beter,

**Comment by arlake228** [comment]
One idea shared from Jon-Paul Herron:
The question on “which half of the square is for which direction” from the workshop yesterday made me wonder….couldn’t you just divide each square in the maddash diagonally instead of horizontally, to give an indication of direction?  

like what’s attached:

![image](https://cloud.githubusercontent.com/assets/634851/8110161/d2a7fe6c-1028-11e5-8e13-cd1ca6456ac4.png)

**Comment by soichih** [comment]
I always gets confused by this, so it's a great idea. However the diagonal icon still doesn't show the direction of the test.. It might be ugly but you could add an arrows?

![mark](https://cloud.githubusercontent.com/assets/923896/8111232/a6745b64-102e-11e5-8f84-0ee04c06103c.png)

**Comment by daldoyle** [comment]
Would the lowest hanging fruit here be just adding the direction information to the hover text? It might not be 100% evident at first glance but at least the hover would make it explicit and serve as an always available reminder.

**Comment by tonin** [comment]
@igarny and I received more requests about making this more obvious from other worshops and trainings too.  I think that @daldoyle suggestion is good.
