### ISSUE TITLE
psUI integration

### ISSUE THREAD

**Issue by arlake228** [perfsonar/maddash#28]
It would be nice if MaDDash could provide link to psUI instance with configurable URL that feeds it the src and dst. Additionally, may be different for certain dashboards.

**Comment by arlake228** [comment]
May need to investigate if authentication works properly allows this. If not authenticated the src and dst are lost.

**Comment by tonin** [comment]
Here is an example of an on demand measurement run in the psUI:

http://ps-ui-test.qalab.geant.net/perfsonar-ui/PerfsonarUI.jsp#bwctl_mp:src=tcp://psmp-gn-bw-01-ath-gr.geant.net:4823&dst=http://62.40.106.187:8090/services/MP/BWCTL&MP=http://62.40.106.187:8090/services/MP/BWCTL&duration=30&interval=6&version=ipv4&protocol=TCP

We'd want most part of that URL to be configurable and build by MaDDash.
