### ISSUE TITLE
The maddash RPM package should open ports 80 and 443

### ISSUE THREAD

**Issue by tonin** [perfsonar/maddash#87]
A default maddash installation should automatically open ports 80 and 443 so that users don't need to do that themselves.

**Comment by arlake228** [comment]
I disagree with this. We have had this type of debate many times for many packages, and packages should not be messing with firewalls, this is why we have a separate firewall package. Not everybody runs firewalld nor wants individual rpms messing with firewall settings.

**Comment by tonin** [comment]
Yes, right, forgot we already had this other issue opened.  Together with https://github.com/perfsonar/project/issues/1219 that will solve this.
