### ISSUE TITLE
MaDDash HTTP reverse proxy does not work with selinux enabled

### ISSUE THREAD

**Issue by arlake228** [perfsonar/maddash#88]
The Apache reverse proxy setup by MaDDash does not work with selinux enabled.

**Comment by tonin** [comment]
I'm trying to replicate this issue, but without luck. Is the reverse proxy used in some other setup than the MaDDash API?

On a clean CentOS7, with packages **perfsonar-toolkit-security** and **maddash** from 4.2.3-nightly, with `getenforce = Enforcing`, I can access the MaDDash API fine.

**Comment by tonin** [comment]
Might not have been related to SElinux but to https://github.com/perfsonar/maddash/issues/89
Closing for now, we can re-open if there's a clear way to replicate.
