### ISSUE TITLE
Customized colors for Maddash graph

### ISSUE THREAD

**Issue by BichyRichy** [perfsonar/maddash#97]
The graphs on our Maddash site currently display throughput for multiple tool names, as shown [here](https://i.imgur.com/AdasulC.jpeg).  However, all our custom tools show as the same color orange. Is it possible to define custom colors for each tool to differentiate between them in the graph?

![image](https://user-images.githubusercontent.com/14113568/98166400-580b9500-1eb5-11eb-8567-6e745ba1f9f6.jpg)

**Comment by tonin** [comment]
Issue moved to [perfsonar/graphs #168](https://github.com/perfsonar/graphs/issues/168) via [**ZenHub**](https://www.zenhub.com/)
